# SPDX-FileCopyrightText: 2026 Daniel Hast
#
# SPDX-License-Identifier: GPL-3.0-only

# Generated by rust2rpm 28
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0

%global crate syd

Name:           rust-syd
Version:        3.49.1
Release:        %autorelease
Summary:        Rock-solid application kernel

License:        GPL-3.0-only
URL:            https://crates.io/crates/syd
Source0:        %{crates_source}
Source1:        syd-%{version}-vendor.tar.xz
Source2:        COPYING

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  libseccomp-devel

%global _description %{expand:
Rock-solid application kernel.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
### BEGIN LICENSE SUMMARY ###
# (MIT OR Apache-2.0) AND Unicode-3.0
# 0BSD
# 0BSD OR MIT OR Apache-2.0
# Apache-2.0
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause
# BSD-2-Clause OR Apache-2.0 OR MIT
# BSD-3-Clause
# CC0-1.0
# GPL-3.0-only
# GPL-3.0-or-later
# ISC
# MIT
# MIT OR Apache-2.0
# MIT OR Apache-2.0 OR LGPL-2.1-or-later
# MIT OR Apache-2.0 OR Zlib
# MIT OR Zlib OR Apache-2.0
# MPL-2.0
# MPL-2.0 OR LGPL-3.0-or-later
# Unlicense OR MIT
# WTFPL
# Zlib
# Zlib OR Apache-2.0 OR MIT
###  END LICENSE SUMMARY  ###
License:        ((MIT OR Apache-2.0) AND Unicode-3.0) AND 0BSD AND (0BSD OR MIT OR Apache-2.0) AND Apache-2.0 AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND BSD-2-Clause AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND BSD-3-Clause AND CC0-1.0 AND GPL-3.0-only AND GPL-3.0-or-later AND ISC AND MIT AND (MIT OR Apache-2.0) AND (MIT OR Apache-2.0 OR LGPL-2.1-or-later) AND (MIT OR Apache-2.0 OR Zlib) AND (MIT OR Zlib OR Apache-2.0) AND MPL-2.0 AND (MPL-2.0 OR LGPL-3.0-or-later) AND (Unlicense OR MIT) AND WTFPL AND Zlib AND (Zlib OR Apache-2.0 OR MIT)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license COPYING
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc ChangeLog.md
%doc README.md
%{_bindir}/syd
%{_bindir}/syd-aes
%{_bindir}/syd-asm
%{_bindir}/syd-aux
%{_bindir}/syd-bit
%{_bindir}/syd-cap
%{_bindir}/syd-cat
%{_bindir}/syd-cpu
%{_bindir}/syd-dns
%{_bindir}/syd-elf
%{_bindir}/syd-emacs
%{_bindir}/syd-env
%{_bindir}/syd-exec
%{_bindir}/syd-fd
%{_bindir}/syd-fork
%{_bindir}/syd-fs
%{_bindir}/syd-hex
%{_bindir}/syd-info
%{_bindir}/syd-key
%{_bindir}/syd-ldd
%{_bindir}/syd-lock
%{_bindir}/syd-ls
%{_bindir}/syd-mdwe
%{_bindir}/syd-mem
%{_bindir}/syd-net
%{_bindir}/syd-oci
%{_bindir}/syd-ofd
%{_bindir}/syd-path
%{_bindir}/syd-pause
%{_bindir}/syd-pds
%{_bindir}/syd-poc
%{_bindir}/syd-pty
%{_bindir}/syd-read
%{_bindir}/syd-rnd
%{_bindir}/syd-run
%{_bindir}/syd-sec
%{_bindir}/syd-sh
%{_bindir}/syd-sha
%{_bindir}/syd-size
%{_bindir}/syd-stat
%{_bindir}/syd-sys
%{_bindir}/syd-tck
%{_bindir}/syd-test
%{_bindir}/syd-test-do
%{_bindir}/syd-tor
%{_bindir}/syd-tsc
%{_bindir}/syd-tty
%{_bindir}/syd-utc
%{_bindir}/syd-uts
%{_bindir}/syd-x

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor
cp %{SOURCE2} .

%build
%cargo_build -f oci
%{cargo_license_summary -f oci}
%{cargo_license -f oci} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install -f oci

%if %{with check}
%check
%cargo_test -f oci
%endif

%changelog
%autochangelog
